#pragma once
/* This is a file generated by IDGen.exe. do not modify it, probably. Or do, it's your funeral. */
/* ========== Entities ========== */
constexpr u16 ID_REDNECK = 1000;

/* ========== Tiles ========== */
constexpr u16 ID_BRICKS = 1;
constexpr u16 ID_GRASS1 = 2;
constexpr u16 ID_GRASS2 = 3;
constexpr u16 ID_BONGO1 = 4;
constexpr u16 ID_BONGO2 = 5;
constexpr u16 ID_CONCRETE = 6;

